// var instructors = [
//   { name: 'Erin', location: 'DC', lunch: 'dumplings duh' },
//   { name: 'Zakk', location: 'DC', lunch: 'also dumplings' },
//   { name: 'Hammad', location: 'MD', lunch: 'homemade delicacies' },
//   { name: 'John', location: 'DC', lunch: 'something healthy in a mason jar' }
// ]

var triviaQuestions = [
	{ number: "1.", question: "Who designed what was considered the world’s first car?", possibilities: ['Henry Ford', 'Ferdinand Porsche', 'Karl Benz', 'Louis Chevrolet'], key: 3, amplifyingInfo: "Designed, built and patented by Karl Benz in 1886, the Benz Patent-Motorwagen is universally recognized as the first internal combustion automobile. In 1926, Karl Benz and Gottlieb Daimler would join forces and company’s, creating Daimler-Benz, later Mercedes-Benz."},
	{ number: "2.", question: "What famous auto maker is responsible for designing the Volkswagen Beetle?", possibilities: ['Bavarian Motor Works', 'Walter P. Chrysler', 'Henry Ford', 'Ferdinand Porsche'], key: 2, amplifyingInfo: "Not his most luxurious or fastest automotive design, Ferdinand Porsche, legacy to Porsche Motors and some of the most luxurious and sought after sports cars in the world, did in fact design the Volkswagen Beetle, contracted by Adolf Hitler."},
	{ number: "3.", question: "Who did Ford enlist to help design their Ferrari-beating car in the 1960's?", possibilities: ['Carroll Shelby', 'John DeLorean', 'Lee Iacocca', 'Louis Chevrolet'], key: 0, amplifyingInfo: "Ford enlisted automaker Carroll Shelby to help design a vehicle that would take out Ferrari. Their early attempts in 1964 proved disastrous and they didn't even finish the race. Shelby, however, had won the Le Mans GT class and helped Ford down a new path to victory. Here, Shelby is driving an Aston Martin DBR1/1 for the Aston Martin factory team at the 12 Hours of Sebring on March 22, 1958, and in 2007."},
	{ number: "4.", question: "How did the Ford Mustang get it’s name?", possibilities: ['Herd of Wild Horses', 'WWII Fighter Plane', 'Henry Ford’s Wife', 'Play on words for Horsepower'], key: 1, amplifyingInfo: "Ford executive stylist John Najjar is credited with naming the Mustang. Najjar was said to be a fan of the WWII-winning P-51 Mustang fighter plane, thus using the powerful moniker for Ford’s iconic and first of the Pony cars."},
	{ number: "5.", question: "Which car is considered to be the first “muscle car”?", possibilities: ['1964 Pontiac GTO', '1962 Chevrolet Impala', '1967 Chevrolet Camaro', '1964 Ford Mustang'], key: 0, amplifyingInfo: "Although there had been powerful cars built up to this point, it is the 1964 Pontiac GTO, which is recognized as the first true Muscle car. With an advertising and marketing campaign stating the facts, the midsize Pontiac Tempest/LeMans could be optioned with the GTO package, featuring a 389ci Tri-power (3-dual carburetors) engine, dual exhaust and hood scoops."},
	{ number: "6.", question: "As of 2015, what is the worlds largest automotive company?", possibilities: ['Volkswagen Group', 'General Motors', 'Ford Motors', 'Toyota Motor'], key: 3, amplifyingInfo: "As of 2015, Toyota is the worlds largest automaker followed by General Motors who just recently ranked ahead of Volkswagen Group.  The Toyota Corolla remains the best selling car in the world with 1.02 million units sold."},
	{ number: "7.", question: "What company opened up the first drive-in gas station?", possibilities: ['Mobile', 'Exxon', 'Shell', 'Gulf'], key: 3, "Gulf opened up the first station in Pittsburg, PA in 1913."},
	{ number: "8.", question: "What was the race that Ford wanted to win to show up Ferrari?", possibilities: ['Indy 500', 'Monaco Grand Prix', '24 Hours of Le Mans', '24 at Daytona'], key: 2, amplifyingInfo: "The 24 Hours of Le Mans had been won by Ferrari every year from 1960 to 1965. Ford wanted to show them up for the 1966 race by designing a car that could take them out of the running."},
	{ number: "9.", question: "The famous Safari Rally was held in which country during the 1990s?", possibilities: ['South Africa', 'Morocco', 'Mexico', 'Kenya'], key: 3, amplifyingInfo: "The Safari Rally of Kenya. The event was the longest in the championship. The shorter Anatolian Turkey Rally replaced the Safari Rally in the 2003 championship."},
	{ number: "10.", question: "What is the name of the caped lady on top of the Rolls Royce radiators?", possibilities: ['Flying Woman', 'Queen Elizabeth', 'Spirit of Ecstasy', 'Lady Liberty'], key: 3, amplifyingInfo: "The Spirit of Ecstasy is the official name for the woman mascot hood ornament seen on many Rolls Royces."},
	{ number: "11.". question: "Who originally founded Tesla?", possibilities: ['Elon Musk & Martin Eberhard', 'J.B. Straubel & Ian Wright', 'Martin Eberhard & Marc Tarpenning'], key: 3, amplifyingInfo: "Tesla was founded in July 2003, by engineers Martin Eberhard and Marc Tarpenning. Elon Musk, J. B. Straubel and Ian Wright joined the company early on and were retroactively allowed to call themselves co-founders."},
	{ number: "12.", question: "Actor Steve McQueen did his own racing stunts in 'Bullitt' and 'The Great Escape,' but do you know what vehicle he chose when he raced the Baja 1000 in 1969?", possibilities: ['Dune Buggy', 'Dirt Bike', 'Trophy Truck', 'Rally Car'], key: 0, amplifyingInfo: "In addition to his work onscreen. Steve McQueen was also a star in the racing world. While he steered a Ford Mustang through the streets of San Francisco in "Bullitt" and rode a motorcycle in "The Great Escape," McQueen chose a souped-up dune buggy for his 1969 Baja 1000 debut. His Baja Boot made it almost to the end of the race before the transmission blew, forcing him to withdraw."},
	{ number: "13.", question: "Why was a national speed limit of 55 mph enacted in 1974?", possibilities: ['Increase in automobile accidents', 'Increase in speeding tickets', 'Oil Shortage', 'Increase in city traffic'], key: 3, amplifyingInfo: "Oil Shortage.  The National Maximum Speed Law (NMSL) in the United States was a provision of the 1974 Emergency Highway Energy Conservation Act that prohibited speed limits higher than 55 miles per hour (90 km/h). It was drafted in response to oil price spikes and supply disruptions during the 1973 oil crisis.  While officials hoped gasoline consumption would fall by 2.2%, actual savings are estimated at between 0.5% and 1%."},
	{ number: "14.", question: "The first official Lancia Group B rally car was the Lancia Rally -____ ?", possibilities: ['Stratos', 'S4', '037', 'Integrale'], key: 3, amplifyingInfo: "Lancia Rally 037 or Lancia-Abarth #037 from its Abarth project code SE037) was introduced in 1983. A mid-engine sports car and rally car built by Lancia in the early 1980s that competed in the FIA Group B World Rally Championship. It was the last rear-wheel drive car to win the WRC. "},
	{ number: "15.", question: "What was the first Japanese car to be produced in the United States?", possibilities: ['Toyota Camry','Honda Civic', 'Nissan Altima', 'Honda Accord'], key: 3, amplifyingInfo: "In November of 1982, the first American-produced Honda Accord rolled off the assembly line at the Marysville Auto Plant in Ohio, making it the first Japanese car to be produced in the United States. The Accord would prove quite popular. In its first year of production, it became the best-selling Japanese car in the United States — a title which it would hold for the next 15 years."},
	{ number: "16.", question: "What was Henry Ford most famous for?", possibilities: ['Inventing the Automobile', 'Inventing Combustion Engines', 'Development of the assembly line', 'Development of the Ford Mustang'], key: 2, amplifyingInfo: "The “Model-T” was the first car to be mass-produced. Henry Ford introduced the assembly line in December of 1908, and as a result he was not only able to mass-produce the Model-T, but was able to offer it to his customers at a much lower price than the competition. By 1913, Ford was producing half of all cars sold in the United States, and by 1927, he had sold more than 15 million Model-Ts!"},
	{ number: "17.", question: "Who was the first English driver to win the driver's title?", possibilities: ['Tony Pond', 'Colin McRae', 'Richard Burns', 'Jimmy McRae'], key: 2, amplifyingInfo: "Richard Burns won in 2001 and Colin McRae who is Scottish won in 1995. Both were driving a Subaru."},
	{ number: "18.", question: "Tesla, Inc. is named after _______.", possibilities: ['a Magician', 'an astronomer', 'an electrical engineer', 'a mechanical engineer'], key: 2, amplifyingInfo: "Nikola Tesla is best known for his contributions to the design of the modern alternating current (AC) electricity supply system."},
	{ number: "19.", question: "What production car is considered the most winningest racecar in touring and DTM?", possibilities: ['Mercedes 190E EVO II', 'BMW E30 M3', 'Porsche 911 Turbo', 'Nissan Skyline GT-R'], key: 1, amplifyingInfo: "This car is why you care about BMW Motorsport. When the original M3 raced between 1987-1993, it dominated circuits. Multiple Touring Car championships in countries all over Europe, multiple 24 Hours of Nurburgring and Spa wins, and even a couple rally victories."},
	{ number: "20.", question: "Bentley, Bugatti, Lamborghini and Porsche are auto manufacturers under what flagship company?", possibilities: ['Daimler AG', 'Ford Motor Company', 'Volkswagen Group', 'General Motors'], key: 2, amplifyingInfo: "Volkswagen Group sells passenger cars under the Audi, Bentley, the Audi, Bentley, Bugatti, Lamborghini, Porsche, SEAT, Škodaand Volkswagen marques; motorcycles under the Ducati brand; and commercial vehicles under the MAN, Scania,Neoplan and Volkswagen Commercial Vehicles marques.  It is divided into two primary divisions, the Automotive Division and the Financial Services Division, and has approximately 340 subsidiary companies."}
]


